// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIyLjd1sH1hgtLpLOynUT6DHeZPUFLmg',
    appId: '1:124566344864:web:4aee86726d109af06065c5',
    messagingSenderId: '124566344864',
    projectId: 'receivo-expense-tracker',
    authDomain: 'receivo-expense-tracker.firebaseapp.com',
    storageBucket: 'receivo-expense-tracker.firebasestorage.app',
    measurementId: 'G-0C9SL1K67M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALqpfSn9pE6tVz8JK5rnkb1accCnRRstI',
    appId: '1:124566344864:android:f470fc4608672aef6065c5',
    messagingSenderId: '124566344864',
    projectId: 'receivo-expense-tracker',
    storageBucket: 'receivo-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA312Fr76XI3lckjMZruI20V6S6KRfZTUg',
    appId: '1:124566344864:ios:1ef9a5916e013e7b6065c5',
    messagingSenderId: '124566344864',
    projectId: 'receivo-expense-tracker',
    storageBucket: 'receivo-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.receivoExpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA312Fr76XI3lckjMZruI20V6S6KRfZTUg',
    appId: '1:124566344864:ios:1ef9a5916e013e7b6065c5',
    messagingSenderId: '124566344864',
    projectId: 'receivo-expense-tracker',
    storageBucket: 'receivo-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.receivoExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcIyLjd1sH1hgtLpLOynUT6DHeZPUFLmg',
    appId: '1:124566344864:web:6b082476d63727ef6065c5',
    messagingSenderId: '124566344864',
    projectId: 'receivo-expense-tracker',
    authDomain: 'receivo-expense-tracker.firebaseapp.com',
    storageBucket: 'receivo-expense-tracker.firebasestorage.app',
    measurementId: 'G-2JRDZSW9C5',
  );
}
